modLoader = "javafml"
loaderVersion = "[35,)"
license = "All rights reserved"

[[mods]]

modId = "learn-mod"
version = "1.0"
displayName = "Learn Mod"
credits = "theaemogie - aemogie.#7352"
authors = "aemogie."
description = "Mod made by aemogie to learn Modding"